name: Build Angular App and Deploy on Firebase
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03op-T-w5IkYsCgYIARAAGAMSNwF-L9IrkeORM1LV7Yk2SCv0alUTRSVc5k6-1-ZCC2WcYpm_EgckAXsT664uODceG1poJJf4Y3o